version = 0.1

[default.build.parameters]
parallel = true
cached = false
beta_features = true

[default.deploy.parameters]
stack_name = "content-tracking"
profile = "sandbox"
resolve_s3 = true
s3_prefix = "content-tracking"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=sandbox",
  "CampaignRedirectLogGroupName=/newsletter-service/sandbox/campaign-redirect-log-group-name",
  "NewsletterApiBaseUrl=/newsletter-service/sandbox/newsletter-api-base-url",
  "NewsletterMintApiKeySecretArn=/newsletter-service/sandbox/campaign-link-api-key-secret-arn",
  "CampaignShortLinkBase=/newsletter-service/sandbox/campaign-short-link-base",
]

[prod.deploy.parameters]
stack_name = "content-tracking"
resolve_s3 = true
s3_prefix = "content-tracking"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=production",
  "CampaignRedirectLogGroupName=/newsletter-service/production/campaign-redirect-log-group-name",
  "NewsletterApiBaseUrl=/newsletter-service/production/newsletter-api-base-url",
  "NewsletterMintApiKeySecretArn=/newsletter-service/production/campaign-link-api-key-secret-arn",
  "CampaignShortLinkBase=/newsletter-service/production/campaign-short-link-base",
]
